eureka:
  client:
    service-url:
      defaultZone: http://47.106.174.156:8761/eureka/

spring:
  application:
    name: Order
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.102.135.76/sell?characterEncoding=utf8&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8011